---
apiVersion: kustomize.toolkit.fluxcd.io/v1
kind: Kustomization
metadata:
  name: external-dns
spec:
  interval: 1h
  retryInterval: 1m
  timeout: 5m
  prune: true
  wait: true
  sourceRef:
    kind: GitRepository
    name: area-51-flux-sync
  path: infrastructure/controllers/external-dns
  dependsOn:
    - name: metallb
    - name: l2-aware-lb
    - name: pihole
