---
apiVersion: helm.toolkit.fluxcd.io/v2beta1
kind: HelmRelease
metadata:
  name: external-dns
spec:
  interval: 30m
  chart:
    spec:
      chart: external-dns
      version: "1.14.4"
      sourceRef:
        kind: HelmRepository
        name: external-dns
      interval: 12h
  values:
    provider:
      name: pihole
    policy: upsert-only
    registry: noop
    logLevel: trace
    sources:
      - service
      - ingress
    env:
      - name: EXTERNAL_DNS_PIHOLE_SERVER
        value: http://pihole-web.dns.svc.cluster.local
      - name: EXTERNAL_DNS_PIHOLE_PASSWORD
        valueFrom:
          secretKeyRef:
            name: pihole-password
            key: password
