---
apiVersion: cert-manager.io/v1
kind: ClusterIssuer
metadata:
  name: area-51-selfsigned-cluster-issuer
spec:
  selfSigned: {}
---
apiVersion: cert-manager.io/v1
kind: ClusterIssuer
metadata:
  name: area-51-cluster-issuer
spec:
  ca:
    secretName: area-51-ca
