---
apiVersion: helm.toolkit.fluxcd.io/v2beta1
kind: HelmRelease
metadata:
  name: pihole
spec:
  interval: 30m
  chart:
    spec:
      chart: pihole
      version: "2.24.0"
      sourceRef:
        kind: HelmRepository
        name: pihole
      interval: 12h
  values:
    ingress:
      enabled: true
      annotations:
        kubernetes.io/ingress.class: nginx
        cert-manager.io/cluster-issuer: area-51-cluster-issuer
      hosts:
        - pihole.area-51.fr
      tls:
        - hosts:
            - pihole.area-51.fr
          secretName: pihole.area-51.fr
    virtualHost: pihole.area-51.fr
    serviceDns:
      mixedService: true
      loadBalancerIP: 10.42.0.253
      type: LoadBalancer
      extraLabels:
        area-51.fr/service: pihole
    serviceWeb:
      https:
        enabled: false
    doh:
      enabled: true
      envVars:
        { DOH_UPSTREAM: "https://1.1.1.1/dns-query,https://1.0.0.1/dns-query" }
    persistentVolumeClaim:
      enabled: true
      storageClass: openebs-hostpath
