---
apiVersion: kustomize.toolkit.fluxcd.io/v1
kind: Kustomization
metadata:
  name: l2-aware-lb
spec:
  interval: 1h
  retryInterval: 1m
  timeout: 5m
  prune: true
  wait: true
  sourceRef:
    kind: GitRepository
    name: area-51-flux-sync
  path: infrastructure/configurations/l2-aware-lb
  dependsOn:
    - name: metallb
